# Generated by Django 4.2.4 on 2023-08-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('idType', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Weighing',
            fields=[
                ('idWeighing', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('idExpense', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('type_idType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataAnalyzer.type')),
            ],
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('idCattle', models.IntegerField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=45)),
                ('birthDay', models.DateField()),
                ('weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataAnalyzer.weighing')),
            ],
        ),
    ]
