# Generated by Django 4.2.4 on 2023-08-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=8)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Weighing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=45)),
                ('birthDay', models.DateField()),
                ('weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataAnalyzer.weighing')),
            ],
        ),
    ]
