# Generated by Django 4.2.4 on 2023-08-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='idCattle',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='idExpense',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='idType',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weighing',
            name='idWeighing',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
